CREATE TABLE USERS (
  "userID" SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL CHECK(char_length(name) >= 1),
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20),
  address VARCHAR(255),
  role VARCHAR(10) CHECK (role IN ('MEMBER', 'STAFF', 'ADMIN')),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);